version: "3"

volumes:
  # Les statics (favicon, css, js, photos) sont mis-en-cache par nginx dans ce
  # volume.
  staticcache:

services:
  strass:
    image: bersace/strass
    volumes:
    # Les données du site (base, photos, styles, etc.) sont stockées en local et
    # montées dans un volume. Par défaut, on monte les données de dév.
    - ${STRASS_ROOT-./htdocs}:/strass/htdocs
    environment:
      STRASS_ROOT: /strass/htdocs
    labels:
      com.dnsdock.alias: backend.strass.docker

  nginx:
    image: nginx:mainline-alpine
    volumes:
    # Dans le conteneur, nginx sauvegarde les statics dans /var/cache/static. Ça
    # peut vite grossir avec les photos !
    - staticcache:/var/cache/static
    # Cette configuration nginx gère le FCGI et les quelques règles de sécurité.
    # Il a vocation à être mandataire d'un autre nginx pour le SSL par exemple.
    - ./docker/site.conf:/etc/nginx/conf.d/default.conf:ro
    labels:
      com.dnsdock.alias: www.strass.docker
