version: "3"

services:
  strass:
    image: bersace/strass
    labels:
      com.dnsdock.alias: strass.docker
    volumes:
    - ./include/:/strass/include
    - ./index.php:/strass/index.php
    # Les données du site (base, photos, styles, etc.) sont stockées en local et
    # montées dans un volume. Par défaut, on monte les données de dév.
    - ${STRASS_ROOT-./htdocs}:/strass/htdocs
    - ./docker/entrypoint.mk:/usr/local/bin/entrypoint.mk
    - ./docker/php5-fpm-pool.conf:/etc/php5/fpm/pool.d/strass.conf
    - ./docker/php5-fpm.conf:/etc/php5/fpm/php-fpm.conf
    environment:
      STRASS_ROOT: /strass/htdocs
    command: devserver
