INSERT INTO etape
(slug, participe_passe, titre, ordre, sexe, age_min)
VALUES
('promesse', 'a prononcé sa', 'promesse', 0, 'm', 11),
('seconde-classe', 'a obtenue sa', 'seconde classe', 2, 'm', 11),
('premiere-classe', 'a obtenue sa', 'première classe', 3, 'm', 11),
('ep', 'a été admis', 'équipier-pilote', 10, 'h', 16),
('rp', 'a pris son engagement', 'routier-pilote', 11, 'h', 16),
('rs', 'a pris son départ', 'routier-scout', 12, 'h', 18),
('flot-jaune', 'a pris son', 'flot jaune', 10, 'f', 16),
('flot-vert', 'a pris son', 'flot vert', 11, 'f', 16),
('ga', 'a pris son', 'flot rouge', 12, 'f', 16);

INSERT INTO unite_type
(slug, nom, parent, virtuelle, ordre, sexe, age_min, age_max)
VALUES
('groupe',		'groupe',		NULL,	0, 0,  'm', 30, 130),
('clan',		'clan',			NULL,	0, 1,  'h', 17, 50),
('eqclan',		'équipe',		2,	0, 1,  'h', 16, 30),
('feu',			'feu',			NULL,	0, 1,  'f', 17, 30),
('eqfeu',		'équipe',		4,	0, 1,  'f', 16, 30),
('troupe',		'troupe',		1,	0, 2,  'h', 18, 30),
('hp',			'haute-patrouille',	6,	1, 3,  NULL, NULL, NULL),
('patrouille',		'patrouille',		6,	0, 4,  'h', 11, 17),
('compagnie',		'compagnie',		1,	0, 2,  'f', 18, 30),
('hpc',			'haute-patrouille',	9,	1, 3,  NULL, NULL, NULL),
('patguide',		'patrouille',		9,	0, 4,  'f', 11, 17),
('meute',		'meute',		1,	0, 5,  'm', 17, 30),
('sizloup',		'sizaine',		12,	0, 6,  'h', 7, 12),
('clairiere',		'clairière',		1,	0, 5,  'f', 17, 30),
('sizlouvette',		'sizaine',		14,	0, 6,  'f', 7, 12);

INSERT INTO unite_role
(slug, titre, accr, type, acl_role, ordre)
VALUES
('cg',		'chef de groupe',		'CG',	1,	'chef',		0),	-- 1
('acg',		'assistant chef de groupe',	'ACG',	1,	'assistant',	1),
('cc',		'chef de clan',			'CC',	2,	'chef',		10),
('acc',		'assistant chef de clan',	'CCA',	2,	'assistant',	11),
('cer',		'Chef d''équipe',		'ACC',	3,	'chef',		11),
('equipier',	'routier',			'SR',	3,	'assistant',	12),
('cf',		'cheftaine de feu',		'CF',	3,	'chef',		10),
('acf',		'Assistante cheftaine de feu',	'ACF',	4,	'chef',		11),
('cef',		'Cheftaine d''équipe',		'CE',	5,	'chef',		11),
('equipiere',	'guide-aînée',			'GA',	5,	'assistant',	12),
('ct',		'chef de troupe',		'CT',	6,	'chef',		20),
('act',		'assistant chef de troupe',	'ACT',	6,	'assistant',	21),
('cp',		'chef de patrouille',		'CP',	8,	'chef',		40),	-- 15
('sp',		'second de patrouille',		'SP',	8,	'assistant',	41),
('3e-patrouille','3e',				NULL,	8,	'membre',	42),
('4e-patrouille','4e',				NULL,	8,	'membre',	43),
('5e-patrouille','5e',				NULL,	8,	'membre',	44),
('6e-patrouille','6e',				NULL,	8,	'membre',	45),	-- 20
('7e-patrouille','7e',				NULL,	8,	'membre',	46),
('8e-patrouille','8e',				NULL,	8,	'membre',	46),
('ccie',	'cheftaine de compagnie',	'CCie',	9,	'chef',		20),
('accie',	'assistante cheftaine de compagnie','ACCie',9,	'chef',		21),
('ce',		'cheftaine d''équipe',		'CE',	11,	'chef',		40),	-- 25
('se',		'seconde d''équipe',		'SE',	11,	'assistant',	41),
('3e-equipe',	'3e',				NULL,	11,	'membre',	42),
('4e-equipe',	'4e',				NULL,	11,	'membre',	43),
('5e-equipe',	'5e',				NULL,	11,	'membre',	44),
('6e-equipe',	'6e',				NULL,	11,	'membre',	45),	-- 30
('7e-equipe',	'7e',				NULL,	11,	'membre',	46),
('8e-equipe',	'8e',				NULL,	11,	'membre',	47),
('akela',	'Akéla',			NULL,	12, 	'chef',		30),
('acm',		'Assistant d''Akéla',		'ACM',	12,	'chef',		31),
('sizainier-louveteau','sizainier',		NULL,	13,	'membre',	50),	-- 35
('second-louveteau','second',			NULL,	13,	'membre',	51),
('3e-louveteau','3e',				NULL,	13,	'membre',	52),
('4e-louveteau','4e',				NULL,	13,	'membre',	53),
('5e-louveteau','5e',				NULL,	13,	'membre',	54),
('6e-louveteau','6e',				NULL,	13,	'membre',	55),	-- 40
('akelaf',	'Akéla',			NULL,	14,	'chef',		30),
('accl',	'assistante d''Akéla',		NULL,	14,	'chef',		31),
('sizainiere-louvette','sizainière',		NULL,	15,	'membre',	50),
('seconde-louvette','seconde',			NULL,	15,	'membre',	51),
('3e-louvette','3e',				NULL,	15,	'membre',	52),	-- 45
('4e-louvette','4e',				NULL,	15,	'membre',	53),
('5e-louvette','5e',				NULL,	15,	'membre',	54),
('6e-louvette','6e',				NULL,	15,	'membre',	55);

INSERT INTO unite_titre
(slug, nom, role)
VALUES
('aumonier-g',	'aumônier',	2),
('tresorier',	'trésorier',	2),
('materialiste','matérialiste',	2),
('secretaire',	'secrétaire',	2),
('aumonier-c',	'aumônier',	4),	--  clan
('aumonier-f',	'aumônier',	8),	--  feu
('aumonier-t',	'aumônier',	14),	--  troupe
('aumonier-ccie','aumônier',	24),	--  compagnie
('aumonier-m',	'aumônier',	34),	--  meute
('ahdeek',	'Ahdeek',	34),
('baloo',	'Baloo',	34),
('bagheera',	'Bagheera',	34),
('chikai',	'Chikaï',	34),
('chil',	'Chil',		34),
('chunchundra',	'Chunchundra',	34),
('dahinda',	'Dahinda',	34),
('darzee',	'Darzee',	34),
('ferao',	'Ferao',	34),
('gris',	'Frère-Gris',	34),
('hathi',	'Hathi',	34),
('jacala',	'jacala',	34),
('kaa',		'Kaa',		34),
('keego',	'Keego',	34),
('keneu',	'Keneu',	34),
('ko',		'Ko',		34),
('kotick',	'Kotick',	34),
('lardaki',	'Lardaki',	34),
('louie',	'Roi-Louie',	34),
('mang',	'Mang',		34),
('mor',		'Mor',		34),
('mysa',	'Mysa',		34),
('nag',		'Nag',		34),
('oo',		'Oo',		34),
('oonai',	'Oonaï',	34),
('phao',	'Phao',		34),
('phaona',	'Phaona',	34),
('pukeena',	'Pukeena',	34),
('raksha',	'Raksha',	34),
('rama',	'Rama',		34),
('rikki',	'Rikki Tiki Tavi',34),
('sahi',	'Sahi',		34),
('shada',	'Shada',	34),
('shawshaw',	'Shaw Shaw',	34),
('singum',	'Singum',	34),
('sona',	'Sona',		34),
('tegumai',	'Tegumaï',	34),
('tha',		'Thâ',		34),
('thuu',	'Thuu',		34),
('wontolla',	'Won-Tolla',	34),
('aumonier-m',	'aumônier',	42),	--  clairière
('ahdeek',	'Ahdeek',	42),
('baloo',	'Baloo',	42),
('bagheera',	'Bagheera',	42),
('chikai',	'Chikaï',	42),
('chil',	'Chil',		42),
('chunchundra',	'Chunchundra',	42),
('dahinda',	'Dahinda',	42),
('darzee',	'Darzee',	42),
('ferao',	'Ferao',	42),
('gris',	'Frère-Gris',	42),
('hathi',	'Hathi',	42),
('jacala',	'jacala',	42),
('kaa',		'Kaa',		42),
('keego',	'Keego',	42),
('keneu',	'Keneu',	42),
('ko',		'Ko',		42),
('kotick',	'Kotick',	42),
('lardaki',	'Lardaki',	42),
('louie',	'Roi-Louie',	42),
('mang',	'Mang',		42),
('mor',		'Mor',		42),
('mysa',	'Mysa',		42),
('nag',		'Nag',		42),
('oo',		'Oo',		42),
('oonai',	'Oonaï',	42),
('phao',	'Phao',		42),
('phaona',	'Phaona',	42),
('pukeena',	'Pukeena',	42),
('raksha',	'Raksha',	42),
('rama',	'Rama',		42),
('rikki',	'Rikki Tiki Tavi',42),
('sahi',	'Sahi',		42),
('shada',	'Shada',	42),
('shawshaw',	'Shaw Shaw',	42),
('singum',	'Singum',	42),
('sona',	'Sona',		42),
('tegumai',	'Tegumaï',	42),
('tha',		'Thâ',		42),
('thuu',	'Thuu',		42),
('wontolla',	'Won-Tolla',	42);
