version: 2

jobs:
  test:
    working_directoy: /strass
    docker:
    - image: bersace/strass-sdk@sha256:abbf7c203611fa8b4185c2f897e8495b2399308187ddb2a580200ce215b6c615
      environment:
        STRASS_SELENIUM: http://localhost:4444/wd/hub
        STRASS_TEST_SERVER: http://localhost:9000
    - image: selenium/standalone-firefox@sha256:749fb5cc781aa50e78595cb669f242b305603feeda35d0c8860d13a63aace835
    steps:
    - checkout
    - run:
        name: Tester
        command: |
          env|sort
          make test

workflows:
  version: 2
  pipeline:
    jobs:
    - test
