#!/usr/bin/php
<?php /*-*- php -*-*/

$paths = explode(':', get_include_path());
array_shift($paths);
array_unshift($paths, dirname(dirname(dirname(__FILE__))).'/include');
set_include_path(implode(':',$paths));

require_once 'Strass.php';

Strass::bootstrap();

require_once 'Strass/Unites.php';

$config = new Strass_Config_Php('strass');
Zend_Registry::set('config', $config);
Strass_Cache::setup();
$db = Strass_Db::setup();

$document = new Wtk_Document(new Wtk_Metas(array('DC.Title' => 'Erreur fatale')));
$style = $config->get('system/style', 'strass');
$document->setStyle(new Wtk_Document_Style($style));
$document->addStyleComponents('layout', 'minilayout', 'common');
$mouvement = $config->get('system/mouvement', null);
$document->addFlags($mouvement, 'error');
$document->embedStyle();
$document->header->setTitle(new Wtk_Link('/', Strass::getSiteTitle()));
$document->header->addFlags($mouvement);

$dialog = $document->addDialog("Oups !");
$dialog->addFlags('error');
$mail = $config->get('system/admin');
if ($mail)
  $wm = "[mailto:".$mail." webmestre]";
else
  $wm = "webmestre";
$dialog->addSection('aide')
->addText("Vous avez rencontré un gros bug. Merci de le rapporter au ".$wm." !");

$render = Wtk_Render::factory($document, 'Html5');
echo $render->render();
