#!/usr/bin/php
<?php /*-*- php -*-*/

$paths = explode(':', get_include_path());
array_shift($paths);
array_unshift($paths, dirname(dirname(__FILE__)).'/include');
set_include_path(implode(':',$paths));

require_once 'Strass.php';

Strass::bootstrap();
$document = Strass::staticDocument();
$dialog = $document->addDialog("Oups !");
$dialog->addFlags('error');
$config = Zend_Registry::get('config');
$mail = $config->get('system/admin');
if ($mail)
    $wm = "[mailto:".$mail." webmestre]";
else
    $wm = "webmestre";

$dialog->addSection('aide')
->addText("Vous avez rencontré un gros bug. Merci de le rapporter au ".$wm." !");

$render = Wtk_Render::factory($document, 'Html5');
echo $render->render();
