#!/usr/bin/php
<?php /*-*- php -*-*/

$paths = explode(':', get_include_path());
array_shift($paths);
array_unshift($paths, dirname(dirname(__FILE__)).'/include');
set_include_path(implode(':',$paths));

require_once 'Strass.php';

Strass::bootstrap();
$document = Strass::staticDocument('Maintenance');
$dialog = $document->addDialog("Webmestre au travail !");
$dialog->addFlags('warn');
$dialog->addSection('aide')->addParagraph("Le site est actuellement en maintance. Désolé et à bientôt !");
$render = Wtk_Render::factory($document, 'Html5');
echo $render->render();
